name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/minio-backend:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull and restart container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/minio-backend:latest

          docker stop minio-backend || true
          docker rm minio-backend || true

          docker run -d \
            --name minio-backend \
            --network custom_bridge \
            --ip 172.25.0.7 \
            --env-file /home/envs/minio-backend.env \
            -p 7000:8000 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/minio-backend:latest

          sleep 5
          docker ps | grep minio-backend
          docker logs --tail 20 minio-backend